export { default as Clipping } from '@/views/test/Clipping.vue'
export { default as Color } from '@/views/test/Color.vue'
export { default as ContourCut } from '@/views/test/ContourCut.vue'
export { default as Cutting } from '@/views/test/Cutting.vue'
export { default as Dijkstra } from '@/views/test/Dijkstra.vue'
export { default as Folder } from '@/views/test/Folder.vue'
export { default as GltfModel } from '@/views/test/GltfModel.vue'
export { default as MeshCut } from '@/views/test/MeshCut.vue'
